### PR TITLE
fixed logical mistake in save_mclust_plots to make it add suffices to  filenames only when there are more than 1 file

### PR DESCRIPTION
**Pull request by MariBerry**

### CODE REVIEW

**Comment by DrrDom** [comment]
It does not fix anything in my opinion. There is a need to move the check `length(fr_lst) == 1` outside of `for` loop and to change all other parts accordingly.

The file is stored under the given name if there is only one item in `fr_lst`, in all other cases the suffix should be added to a file name.

**Comment by DrrDom** [comment]
I'm confused with double `ggsave` call in line 544. Does this code really work?

**Comment by MariBerry** [comment]
it works, but now i finally know why it writes a file twice! i noticed it and couldnt have  understood!

**Comment by DrrDom** [comment]
Fix this please

**Pull request merged**
